# fly.toml app configuration file generated for beautify-ai-backend on 2025-07-10T18:00:02+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beautify-ai-backend'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  machine_idle_timeout = 3600  # 1 hour in seconds

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[metrics]]
  port = 9091
  path = '/metrics'
